### ISSUE TITLE
Help or instructions page.

### ISSUE THREAD

**Issue by paytonshaltis** [sderacy/gooncard#118]
It may be useful to have a dedicated page that is read-only (like the about us) that includes some instructions for each of the major actions for the site. I think we could even combine the about us and a help page together, but keeping them separate is fine too.

An alternative that could be cool if we have some time is to have a little help icon (?) on each page in some consistent spot that the user can click on to get dedicated help for their current page _only_. This would remove the need for a single page that has all the help information. Definitely open to feedback on this.

**Comment by thadakn1** [comment]
i was thinking of adding a toolbar icon for the settings page (if you guys are okay with it). Similarly, I can also do this "help" icon where the icon is a question mark. 

regarding payton's alternative idea: the "?"/help icon when hovered over can pop open a box/MODAL that has some helpful instructions related specifically to that page the user is on. so this would be different on every page that has different functionality! let me know what you guys think. 

@lelekaz @sderacy @paytonshaltis

**Comment by paytonshaltis** [comment]
> regarding payton's alternative idea: the "?"/help icon when hovered over can pop open a box/MODAL that has some helpful instructions related specifically to that page the user is on. so this would be different on every page that has different functionality!

I think this would be a cool (and maybe not too difficult?) addition to the application!

**Comment by paytonshaltis** [comment]
Here's the [web modal API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal) for creating what looks like really easy modals, maybe check this our for help or inspiration...

**Comment by thadakn1** [comment]
sounds good! i found some easy html/css only modals on codepen i can work with. they're pretty effective and have that hover effect I was talking about. i might just do that but i'll look into this api too

**Comment by sderacy** [comment]
Also I would like to suggest, for the edit accounts page (since I was told that we're doing a help page for each page), it would be good to also tell them which platforms have a supported icon. As the user, it might be nice to know "Gram" works for the Instagram icon or that "Twitt" does not for twitter.

**Comment by thadakn1** [comment]
@sderacy ok will do! just a clarification thing, it won't be a whole other page, it will be a smaller sized module. so because it's smaller, i think the less content the better. but i can make a list view of the platforms with icons and how they should be entered if the user wants the icon to show up.
