### ISSUE TITLE
Add label toggle on display card page.

### ISSUE THREAD

**Issue by paytonshaltis** [sderacy/gooncard#150]
Just a small accessibility option that may improve usability. On the display card page, besides just showing icons for account labels, it may be nice to have a toggle switch that allows a viewer to toggle the actual account labels, so they can see 'Instagram: @paytonshaltis' or 'Twitter: @paytonshaltis' instead of just 'icon @paytonshaltis'.

**Comment by sderacy** [comment]
Where would the toggle go on the page?

I personally would opt for the label to be there so that it's explicitly obvious what each icon is, as some people will not be familiar with all of them.

**Comment by paytonshaltis** [comment]
> Where would the toggle go on the page?
 
We could discuss this, but maybe at the top of the page somewhere. If the user has a lot of accounts, it may not be practical to put this at the bottom.

> I personally would opt for the label to be there so that it's explicitly obvious what each icon is, as some people will not be familiar with all of them.

I'm OK with either one, I think we should see what everyone else thinks too @lelekaz @matyis1 @thadakn1. I figured that having this functionality gives us one more accessibility and shortcut feature: expert users can take advantage of icons only, eliminating redundant information, but newbie users can have both to learn.

**Comment by sderacy** [comment]
> I figured that having this functionality gives us one more accessibility and shortcut feature: expert users can take advantage of icons only, eliminating redundant information, but newbie users can have both to learn.

Gotcha. I think my main motive for pushing for the latter is that in the case of custom accounts where they don't have an obvious icon, it can become very confusing:
![image](https://user-images.githubusercontent.com/25871926/202332380-4bec9e23-32e1-47c9-8b32-e67d03a1f4ae.png)

Like if they had 4 different icons like the bottom one but they weren't all as obvious as a url, then it would be hard to discern which platforms the handles belong to. If you just provide a label for everything from the beginning, then you won't encounter that issue. I am open to hearing what you guys think though.

**Comment by thadakn1** [comment]
i was thinking about this issue for a while, obviously it would look cleaner and consistent with the icon as opposed to text that explicitly indicates the platform. i was wondering what if when the user clicks on the icon, it temporarily shows the platform's name. so it's on the screen, but only if you aren't sure what that icon is representing. i think with the toggle feature, the screen would be overcrowded because it would display all of the platform names - when the highlight should be the account/user handles. lmk what you think @sderacy @paytonshaltis @lelekaz @matyis1

**Comment by sderacy** [comment]
> i was wondering what if when the user clicks on the icon, it temporarily shows the platform's name

I like it but the only issue is that there's currently no way for the user to know that they'd have to click on the icon. 

I agree that there needs to be a better way to show the label, but it looks like there'd be space for the label to exist with the content:

![image](https://user-images.githubusercontent.com/25871926/202550491-d41dd64f-22d0-42ef-816d-903ebec9c877.png)

It looks like the text will just wrap if the value is too long, so I would personally just make sure that the label text and icon stay on one line, and the value can do whatever else.

Keeping this in mind, I still think just showing the label all the time would be a better idea but we can also try to add some sort of text that's like "click me!" by an icon so that it shows the label next to it. The downside to this obviously is that it can still be confusing as the user would have to click an icon whenever they don't understand the meaning of a certain icon.

**Comment by sderacy** [comment]
I think it'd be better to just look at the two options:
![image](https://user-images.githubusercontent.com/25871926/203647620-08637212-b009-4246-9c87-94bad99b76ab.png)
![image](https://user-images.githubusercontent.com/25871926/203647584-20748738-a003-4370-843e-648f1cedbe23.png)

![image](https://user-images.githubusercontent.com/25871926/203647368-706a20de-0b01-4d2f-8bf4-6f8a30f4b56d.png)
![image](https://user-images.githubusercontent.com/25871926/203647450-d22d4e31-a9a5-42ed-af49-fe31cb2d453f.png)

I agree that the second would look less sleek since there's more text that can be redundant, but this is more straightforward than having to click on every icon.

**I don't mind the tooltip idea (after all, we're already using one in the footer), but there should be something explicitly _telling_ the users to click the icon if they don't know what the icon represents.**

If you want to add tool tips, just reuse some of the code in the footer since it's already being used there.

**Comment by lelekaz** [comment]
Yeah I'm down for any of these options. @paytonshaltis @thadakn1 @matyis1 Let us know what your thoughts are on this.

**Comment by sderacy** [comment]
Are we adding the fix for this issue to PR #158 or is this going in a separate PR?

**Comment by nishatreddy** [comment]
tooltips can be hard for screen-readers to capture and this poses an accessibility issue sometimes. looking at the designs that sterly posted, I actually like the idea of having the logo, the platform name, and then the account handle. it looks pretty clean!
