### ISSUE TITLE
Add spacing between buttons on homepage

### ISSUE THREAD

**Issue by thadakn1** [sderacy/gooncard#165]
- I tried adding a dark-outline to the casual, professional, all, and none buttons which helped with spacing in dark mode (i added btn-outline-dark) (img 1). However, when i checked how it looks in light mode, the text gets darkened and is hard to read. this doesn't resolve the spacing issue in light mode (i added btn-outline-light which helped for light mode, but there can only be one outline style at any time) (img 2).
- does anyone have any suggestions on how we can go about this issue, or if we even should? @lelekaz @sderacy 
- maybe one approach is changing the padding amount when the app is in mobile view or any non-desktop view? maybe this can be done with a media query or something
<img width="213" alt="Screen Shot 2022-11-29 at 6 23 18 PM" src="https://user-images.githubusercontent.com/57613959/204670576-6c6a48fd-ecd8-401c-8167-6dc59f45a0a4.png">
<img width="189" alt="Screen Shot 2022-11-29 at 6 23 35 PM" src="https://user-images.githubusercontent.com/57613959/204670579-8decd9a0-fb01-4f05-8ed2-fcea1718bf8d.png">

**Comment by sderacy** [comment]
Changing the spacing shouldn't be causing this issue. What code was added specifically?

**Comment by nishatreddy** [comment]
that's not what i meant, i meant when you're on the mobile view for the home page the buttons look smushed. i was trying to resolve this by adding an outline that separates the microphone buttons, but that outline doesn't work well due to the light theme and dark theme settings. so i was wondering if we should look into this issue or just ignore it. im fine with either.
<img width="178" alt="Screen Shot 2022-11-30 at 12 55 24 PM" src="https://user-images.githubusercontent.com/74932567/204872539-cdfe0c3b-f33c-4591-8c38-d5ea75c271da.png">

**Comment by sderacy** [comment]
Gotcha, admittedly I only caught this:
>  However, when I checked how it looks in light mode, the text gets darkened and is hard to read. this doesn't resolve the spacing issue in light mode

and responded to just that. I can go in and fix it. Let me know when you push your changes up.

**Comment by nishatreddy** [comment]
@sderacy just pushed all my changes, lmk what you think. and if its good you can just fix the microphone button thing.

**Comment by sderacy** [comment]
@nishatreddy I'll take a look in a bit. Before I go in, what's wrong with the microphone button?

**Comment by nishatreddy** [comment]
oh whoops i meant all the buttons like professional, casual, microphone etc. my bad.
