### ISSUE TITLE
Potentially refactor JS code on the settings page.

### ISSUE THREAD

**Issue by paytonshaltis** [sderacy/gooncard#57]
Should look into how much more code it will be to move the option defaults to a JS file and have that file call the API for the settings.

**Comment by paytonshaltis** [comment]
Although the EJS code within the settings page isn't the prettiest, it is the most functional in terms of our situation. I experimented with moving things to the client-side `main.js` file:
- If the code is moved to `main.js`, an additional API request is made to fetch the user's settings from the database. This is an asynchronous action, which means that once the settings page loads, the selection options will not be updated until the settings are retrieved from the database.
- If the code is kept in `index.ejs`, the render process can simply use the settings values that are given to the template, construct the HTML file on the backend, and send this to the user, meaning that when they get the file, it will have the correct data inside of it without any delay between a blank option and what their current value is.

The only reason things look a little messy in the EJS file is because Prettier auto-formats EJS to HTML, so line breaks and indentation used in JS won't appear within the `<% %>` inside of the EJS file. I think that just dealing with this is the best action, otherwise, we lose the power of Express handling user sessions within EJS files directly.

**Comment by sderacy** [comment]
> The only reason things look a little messy in the EJS file is because Prettier auto-formats EJS to HTML,

The reason why things look messy is because there's logic within the HTML page, but I think according to what you've found, it's the best option. I was generally opposed to the initial implementation since you needed to have an if else for every single option, and it felt like there must have been a better way to do it.

What we have now is pretty solid and like I said before, it's alright if it's not enterprise level since we do have like a month left to implement everything. I'd rather there be logic that results in a faster overall execution time than make it look pretty and make life a lot harder for us in the long run.

Thanks for taking a look into this Payton, this at least helped me in terms of thinking about the tradeoffs between embedding js directly and using a separate file.

**Comment by sderacy** [comment]
As a quick aside, it's actually also pretty common that in commercial applications (like what this would be if we ever implemented it lol), the CSS is not stored in a separate stylesheet. The classes and styles are actually applied directly to the element because it saves time since you don't have to build each stylesheet.

Your findings make a lot of sense so I'm fine with it the way it is
