### ISSUE TITLE
Readme Update/Restructuring

### ISSUE THREAD

**Issue by thadakn1** [sderacy/gooncard#82]
-i'm going to update the readme, but i just wanted everyone's input on what they think I should include on it (apart from what is already there)
- should i talk about the pages and their functionality? the accessibility concerns? not entirely sure what to put on the readme as of now

let me know what you think @paytonshaltis @lelekaz @sderacy @matyis1

**Comment by sderacy** [comment]
1. I think the instructions are a little confusing right now, like technically you don't need to run `npm run cleanStart` to seed the database but it says it should. We should probably combine setting up the DB and starting the server into one section instead of 2 sections in 2 different places.
2. Accessibility concerns would be a good topic to cover
3. The routes have changed.
4. It would be good to explain the potential use cases for the application (how you use it, etc.)

**Comment by sderacy** [comment]
I think it'd be hard to articulate everything that I'd like to add / change so that's why I think it'd just be better to go in and do it myself once you have the branch up

Then it'll be much easier for others to add and remove stuff since this PR won't be linked to any other code functionalities :)

**Comment by thadakn1** [comment]
Awesome! i'll just create the branch and add the points you listed above and everyone else can add to that branch whenever they feel :)
