### ISSUE TITLE
Add API endpoint for returning the user's settings.

### ISSUE THREAD

**Issue by paytonshaltis** [sderacy/gooncard#85]
Though the user's settings could be accessed in EJS files normally, making data available in the `main.js` files requires explicit API endpoints to be set up.

In order to implement settings changes as referenced in issues #7, #8, and #62, an endpoint must be set up to return the currently logged-in user's settings object. This should probably be done in the `profile.js` file. Below is some information on the endpoint itself:

- The endpoint should be done through the GET method, since the request coming from `main.js` requires information.
- The endpoint should be called `/account/profile/getsettings`, in a similar naming convention to the other endpoints on this page.
- The endpoint should use the `isLoggedIn` middleware that makes sure that a user is logged in before continuing.
- No body is needed for this endpoint; the user is already known server-side, so we can get the email automatically. This is why we need to use the middleware above, otherwise, the user will not be known.
- ~~The endpoint should get the user from the database using the `getUser(`) function, passing it a parameter of `req.session.user.email`.~~
- The settings can actually just be retrieved from `req.session.user.settings` since the middleware makes sure that the user is logged in already.
- The endpoint should return _just_ the **parsed** version of the settings field from the function above, that way the caller can just access the setting properties outright. Normally, this object is stored in the database as a string, so the `JSON.parse()` function will be needed to do this.

**Comment by sderacy** [comment]
@paytonshaltis  I had a question and I wanna preface it by saying I totally get it if you want to keep things the way they are, but if we're adding an API call to return the settings, would it be better to keep the logic for displaying the saved settings on the .ejs file or move the logic to the .js file?

I meant it when I said that I was fine with what we have now, but since we're allowing the .js files to use the user's settings, it makes sense to revisit that conversation.

I am keeping in mind that we have a relatively short deadline to implement everything so I understand delaying or not wanting to change what we currently have

**Comment by paytonshaltis** [comment]
> @paytonshaltis I had a question and I wanna preface it by saying I totally get it if you want to keep things the way they are, but if we're adding an API call to return the settings, would it be better to keep the logic for displaying the saved settings on the .ejs file or move the logic to the .js file?

This is actually a really good point; it may make sense to move to the main.js file. I'll create an issue and assign it to Milestone 3, and if we really do end up running low on time we can leave it as is, but I think this is a good thing to refactor. 

Good call Sterly!

**Comment by matyis1** [comment]
i made a pull request for this issue
